apiVersion: skaffold/v2alpha4
kind: Config
build:
  artifacts:
  - image: frontend
    context: controllers/web
  - image: mask-rcnn
    context: models/mask-rcnn
  - image: yolov3
    context: models/yolo_v3
  - image: mirror
    context: models/mirror
  - image: openpose
    context: models/openpose
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes/web-deployment.yaml
profiles:
- name: gpu
  build:
    artifacts:
    - image: frontend
      context: controllers/web
    - image: mask-rcnn-gpu
      context: models/mask-rcnn
      docker:
        dockerfile: Dockerfile.gpu
    - image: openpose-gpu
      context: models/openpose
      docker:
        dockerfile: Dockerfile.gpu
  deploy:
    kubectl:
      manifests:
      - ./kubernetes/web-deployment-gpu.yaml
