apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: ssl-certificate
spec:
  domains:
    #- DNS name here
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: # create me with `gcloud compute addresses create bank-address --global`
    networking.gke.io/managed-certificates: ssl-certificate
spec:
  backend:
    serviceName: frontend-nodeport
    servicePort: 8080
